# Generated by Django 4.2.1 on 2023-05-27 10:20

from django.db import migrations, models
import django.db.models.deletion
import messaging.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.IntegerField(default=messaging.models.Chat.make_chatId, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversTT', to='signUp.teacher')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersTT', to='signUp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversTS', to='signUp.student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersTS', to='signUp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='MessageST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversST', to='signUp.teacher')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersST', to='signUp.student')),
            ],
        ),
        migrations.CreateModel(
            name='MessageSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date sent')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messaging.chat')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiversSS', to='signUp.student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendersSS', to='signUp.student')),
            ],
        ),
    ]
