# Generated by Django 4.0 on 2023-05-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='students', to='signUp.Course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='quizzes',
            field=models.ManyToManyField(related_name='students', to='classroom.Quiz'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='assignedCourses',
            field=models.ManyToManyField(blank=True, related_name='assignedTeachers', to='signUp.Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='courses',
            field=models.ManyToManyField(related_name='teachers', to='signUp.Course'),
        ),
    ]
